baseURL = "https://www.dwaynemoore.me/"
languageCode = "en-us"
title = "I am Dwayne"
theme = "minimal"
googleAnalytics = ""

[params]
    author = "Calin Tataru"
    description = ""
    githubUsername = "#"
    accent = "red"
    showBorder = true
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "default"
    highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift"]

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/about/"
    name = "About"
    weight = 2

[[menu.main]]
    url = "/post/"
    name = "Posts"
    weight = 3

[[menu.main]]
    url = "/causes/"
    name = "Causes"
    weight = 4

# Social icons to be shown on the right-hand side of the navigation bar.
# The "name" field should match the name of the icon in Font Awesome.
# The list of available icons can be found at http://fontawesome.io/icons.

[[menu.icon]]
    url = "mailto:dwayne@dwaynemoore.me"
    name = "fas fa-envelope"
    weight = 1

[[menu.icon]]
    url = "https://twitter.com/DwayneEMoore/"
    name = "fab fa-twitter"
    weight = 2

[[menu.icon]]
    url = "https://www.linkedin.com/in/dwaynemoore/"
    name = "fab fa-linkedin"
    weight = 3

[[menu.icon]]
    url = "https://www.facebook.com/dwaynem/"
    name = "fab fa-facebook"
    weight = 4

[[menu.icon]]
    url = "https://www.instagram.com/DwayneEMoore/"
    name = "fab fa-instagram"
    weight = 5